name: adrinolinq_owner
description: "A Flutter app scaffolded by flutter_blueprint with Riverpod."
publish_to: "none"

version: 0.1.0+1

environment:
          sdk: ">=3.3.0 <4.0.0"
          flutter: ">=3.24.0"

dependencies:
          flutter:
                    sdk: flutter
          provider: ^6.1.4
          shared_preferences: ^2.2.3
          flutter_secure_storage: ^9.2.2
          equatable: ^2.0.5
          dio: ^5.5.0
          connectivity_plus: ^6.0.5
          pretty_dio_logger: ^1.4.0
          flutter_svg: ^2.0.10+1
          flutter_riverpod: ^3.0.3
          intl: ^0.18.1
          cached_network_image: ^3.2.3
          image_picker: ^1.0.7
          permission_handler: ^11.3.1
          file_selector: ^0.9.5
          hive: ^2.2.3
          hive_flutter: ^1.1.0
          path_provider: ^2.1.2
          crop_your_image: ^2.0.0

dev_dependencies:
          flutter_test:
                    sdk: flutter
          flutter_lints: ^5.0.0
          flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
          android: true
          ios: true
          image_path: "assets/icons/Logo.png"
          min_sdk_android: 21
          remove_alpha_ios: true
          background_color: "#030107"
          adaptive_icon_background: "#030107"
          adaptive_icon_foreground: "assets/icons/Logo.png"
          web:
                    generate: false
          windows:
                    generate: false
          macos:
                    generate: false

flutter:
          uses-material-design: true
          assets:
                    - assets/images/
                    - assets/icons/
                    - assets/fonts/
                    - assets/gifs/
          fonts:
                    - family: SFProRounded
                      fonts:
                                - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
                                  weight: 100
                                - asset: assets/fonts/SF-Pro-Rounded-Light.otf
                                  weight: 300
                                - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
                                  weight: 400
                                - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
                                  weight: 500
                                - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
                                  weight: 600
                                - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
                                  weight: 700
                    - family: Reglo-Bold
                      fonts:
                                - asset: assets/fonts/Reglo-Bold.otf
                                  weight: 900
